In [1]:
! pip install kaggle
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"jogukhee","key":"4ee24c016d928635487940a06fd70feb"}'}

In [2]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

!kaggle competitions list

ref                                            deadline             category            reward  teamCount  userHasEntered  
---------------------------------------------  -------------------  ---------------  ---------  ---------  --------------  
contradictory-my-dear-watson                   2030-07-01 23:59:00  Getting Started     Prizes        107           False  
gan-getting-started                            2030-07-01 23:59:00  Getting Started     Prizes        212           False  
tpu-getting-started                            2030-06-03 23:59:00  Getting Started  Knowledge        573           False  
digit-recognizer                               2030-01-01 00:00:00  Getting Started  Knowledge       3520           False  
titanic                                        2030-01-01 00:00:00  Getting Started  Knowledge      28495            True  
house-prices-advanced-regression-techniques    2030-01-01 00:00:00  Getting Started  Knowledge       7289            True  
connectx

In [3]:
! kaggle competitions download -c 2021-ml-p3

  0% 0.00/6.35k [00:00<?, ?B/s]
100% 6.35k/6.35k [00:00<00:00, 11.2MB/s]
  0% 0.00/110k [00:00<?, ?B/s]
100% 110k/110k [00:00<00:00, 34.7MB/s]
  0% 0.00/32.6k [00:00<?, ?B/s]
100% 32.6k/32.6k [00:00<00:00, 30.1MB/s]


In [4]:
import numpy as np
import pandas as pd

xy = pd.read_csv('train.csv')
#print(xy)
X = xy.loc[:,'N':'rainfall']
#print(xy.dtypes)
#X = np.array(X)

y = xy.loc[:, 'label']

print(X[:5])
print(y[:10])
print(X.shape)
print(y.shape)

    N    P    K  temperature   humidity        ph    rainfall
0  22   36   16    30.581395  50.771481  8.184229   64.585596
1  18   27   41    22.365094  92.308824  7.175344  104.821633
2  61   68   50    35.214628  91.497251  6.793245  243.074507
3  26   72   22    28.767949  37.577921  4.674942   91.720849
4   2  140  197    22.697801  92.822234  5.534567  105.050823
0      mothbeans
1    pomegranate
2         papaya
3     pigeonpeas
4          apple
5    kidneybeans
6         orange
7      mothbeans
8           rice
9       mungbean
Name: label, dtype: object
(1650, 7)
(1650,)


In [5]:
from sklearn.preprocessing import LabelEncoder 
import numpy as np 
classle=LabelEncoder() 
y=classle.fit_transform(y.values) 
print(np.unique(y)) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


In [6]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=1, stratify=y)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1155, 7)
(495, 7)
(1155,)
(495,)


In [7]:
from sklearn.neighbors import KNeighborsClassifier  
knn=KNeighborsClassifier(n_neighbors=5,p=1)  
knn.fit(X_train,y_train) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=1,
                     weights='uniform')

In [8]:
y_train_pred=knn.predict(X_train)
y_test_pred=knn.predict(X_test)  
print('Misclassified training samples: %d' %(y_train!=y_train_pred).sum()) 
print('Misclassified test samples: %d' %(y_test!=y_test_pred).sum()) 

Misclassified training samples: 9
Misclassified test samples: 11


In [9]:
from sklearn.metrics import accuracy_score   
print(accuracy_score(y_test,y_test_pred)) 

0.9777777777777777


In [14]:
from sklearn.metrics import confusion_matrix
conf=confusion_matrix(y_true=y_test,y_pred=y_test_pred) 
print(conf)

[[21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0 21  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [15]:
# 전체 데이터에 적용
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5,p=1) 
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=1,
                     weights='uniform')

In [16]:
test = pd.read_csv('test.csv')


print(test)
print(test.shape)

       N    P    K  temperature   humidity        ph    rainfall
0    101   17   47    29.494014  94.729813  6.185053   26.308209
1     98    8   51    26.179346  86.522581  6.259336   49.430510
2     59   62   49    43.360515  93.351916  6.941497  114.778071
3     44   60   55    34.280461  90.555616  6.825371   98.540477
4     30  137  200    22.914300  90.704756  5.603413  118.604465
..   ...  ...  ...          ...        ...       ...         ...
545  100   32   26    25.234661  57.531615  6.043486  124.226174
546   50   46   52    31.182984  90.216469  6.734006   54.018724
547   30   65   82    20.714244  15.278241  7.103798   76.778887
548   93   26   27    24.592457  56.468296  7.288212  137.704405
549   63   47   35    26.985822  89.055879  7.432768  193.877871

[550 rows x 7 columns]
(550, 7)


In [17]:
test_pred=knn.predict(test)#train data의 y값 예측치
test_pred=classle.inverse_transform(test_pred)

In [18]:
sample = pd.read_csv('sample.csv')
for i in range(len(test_pred)):
  sample['label'][i] = test_pred[i]
sample.head(10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


id       label
0   0   muskmelon
1   1  watermelon
2   2      papaya
3   3      papaya
4   4       apple
5   5       mango
6   6       apple
7   7   mothbeans
8   8    mungbean
9   9      lentil

In [19]:
sample.to_csv('sample.csv', mode='w', index=False)